**Ques 1. What is a Python library? Why do we use Python libraries?**

python library means there is some inbuilt python programs which can be used reusable.The programs written in these libraries are highly optimized.

**Why we use :**

1.Highly optimized function written in python libraries.

2.These can be reusable.

3.Easy to perform any calculation based problems.

4.Faster than our own function beacsuse it will take less space and time.


**Ques 2. What is the difference between Numpy array and List?**

**There are some differences between numpy array and list:**

1.Numpy array used to store only homogeneous data whereas list can store different data type.

2.Numpy array is faster than the list because it stores only same type of data.

3.In Numpy array,no vectorization is happen (calculation used to do row wise) but in list vectorization is there.

4.Numpy array has statistically defined memory allocation whereas in list there is random allocation of the memory.


**Ques 3. Find the shape, size and dimension of the following array?**

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [ ]:
import numpy as np

In [ ]:
arr=np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])

In [ ]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
np.shape(arr)

(3, 4)

In [ ]:
np.size(arr)

12

In [ ]:
np.ndim(arr)

2

**Ques 4. Write python code to access the first row of the following array?**

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [ ]:
arr1=np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])

In [ ]:
arr1[0]

array([1, 2, 3, 4])

**Ques 5. How do you access the element at the third row and fourth column from the given numpy array?**

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [ ]:
arr2=np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])

In [ ]:
arr2[2][3]

12

**Ques 6. Write code to extract all odd-indexed elements from the given numpy array?**

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [ ]:
arr3=np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])

In [ ]:
arr3

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
arr3[0][0]

1

In [ ]:
arr3[0][2]

3

In [ ]:
odd_indexed_elements=arr3[1::2,1::2]

In [ ]:
odd_indexed_elements

array([[6, 8]])

**Ques 7. How can you generate a random 3x3 matrix with values between 0 and 1?**

In [ ]:
import random

In [ ]:
np.random.randn(3,3)

array([[ 1.54818353,  0.07982273,  1.43768925],
       [-0.13648034, -1.31799582, -1.16549067],
       [ 1.60737637, -0.0823297 ,  0.51609074]])

**Ques 8. Describe the difference between np.random.rand and np.random.randn?**

**np.random.rand**

1.generates random numbers uniformly distributed in the range (0,1).

**2.Syntax :**

np.random.rand(3, 3)


**np.random.randn**

1.Generates random numbers from a standard normal distribution (Gaussian distribution with mean = 0 and standard deviation = 1)

**2.Syntax :**

np.random.rand(3, 3)



**9. Write code to increase the dimension of the following array?**

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [ ]:
a=np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
np.expand_dims(a,axis=0)

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

**10. How to transpose the following array in NumPy?**

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [ ]:
b=np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])

In [ ]:
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
b.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

**11. Consider the following matrix:**

**Matrix A:**

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

**Matrix B:**

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]


In [ ]:
Matrix_A=np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
Matrix_B=np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])

In [ ]:
Matrix_A

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
Matrix_B

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

**Perform the following operation using Python:**

In [ ]:
# 1.Index wise multiplication

np.multiply(Matrix_A ,Matrix_B)

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])

In [ ]:
Matrix_B=Matrix_B.T

In [ ]:
# 2.Matrix multiplication

result=Matrix_A @ Matrix_B
result

array([[ 30,  70, 110],
       [ 70, 174, 278],
       [110, 278, 446]])

In [ ]:
# 3.Add both the matrics
Matrix_B=np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])

In [ ]:
Matrics_sum=Matrix_A + Matrix_B
Matrics_sum

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

In [ ]:
# 4.Subtract matrix B from A
Matrics_subtract=Matrix_A - Matrix_B
Matrics_subtract


array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [ ]:
# 5.Divide Matrix B by A
Matrics_divide=Matrix_B / Matrix_A
Matrics_divide


array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

**12. Which function in Numpy can be used to swap the byte order of an array?**

In [2]:
import numpy as np

# Create an array
arr = np.array([1, 256, 65536], dtype=np.int32)

print("Original array:")
print(arr)

# Swap byte order
arr.byteswap(inplace=True)

print("Array after byte swapping:")
print(arr)


Original array:
[    1   256 65536]
Array after byte swapping:
[16777216    65536      256]


**13. What is the significance of the np.linalg.inv function?**

1.This function is used to computes the inverse of square matrix.The np.linalg.inv function inverts the given matrix and inverts the inverted matrix.

2.It is useful in solving systems of linear equation,transforming data,or finding solutions to mathematical problems involving matrices.

In [5]:
# Define a square matrix
A = np.array([[3,4], [5, 6]])

# Compute the inverse
A_inv = np.linalg.inv(A)

print("Matrix A:")
print(A)

print("\nInverse of A:")
print(A_inv)

# Verify the result (A @ A_inv should be the identity matrix)
identity = np.dot(A, A_inv)
print("\nA * A_inv:")
print(identity)

Matrix A:
[[3 4]
 [5 6]]

Inverse of A:
[[-3.   2. ]
 [ 2.5 -1.5]]

A * A_inv:
[[ 1.0000000e+00 -8.8817842e-16]
 [ 0.0000000e+00  1.0000000e+00]]


**14. What does the np.reshape function do, and how is it used?**

reshape() function is used to create a new array of same size but of different desired dimensions.

In [6]:
# Original array
arr = np.array([1, 2, 3, 4, 5, 6])

# Reshape into 2x3 array
modified_array = np.reshape(arr, (2, 3))

print("Original Array:")
print(arr)

print("\nReshaped Array (2x3):")
print(modified_array)


Original Array:
[1 2 3 4 5 6]

Reshaped Array (2x3):
[[1 2 3]
 [4 5 6]]


**15. What is broadcasting in Numpy?**

Broadcasting is a feature in NumPy that allows arrays of different shapes to be combined in arithmetic operations.

In [7]:
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([1, 2, 3])
result = A + B

print(result)

[[2 4 6]
 [5 7 9]]
